### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by idkjs** [lpalmes/graphqlba-apollo-relay#2]
I did this exact same thing. My project is here: https://github.com/idkjs/apollo-relay-mongodb-mashup. I ran your project and I get the same issue I am getting which is that subscriptions keep closing before connection or don't get reached. Have you figured that out yet?

This is the output on your project.

```bsh
WebSocket connection to 'ws://192.168.1.103:4000/subscriptions' failed: WebSocket is closed before the connection is established.
12:29:14.127
client.js:421 WebSocket connection to 'ws://192.168.1.103:4000/subscriptions' failed: Error in connection establishment: net::ERR_ADDRESS_UNREACHABLE
12:29:25.300
client.js:421 WebSocket connection to 'ws://192.168.1.103:4000/subscriptions' failed: Error in connection establishment: net::ERR_ADDRESS_UNREACHABLE

```

**Comment by lpalmes** [comment]
Hey @idkjs, i didn't have that problem, only when i got it up in a vps server, i'm going to take a look and let you know if i solve it, thanks for the input! :)

**Comment by idkjs** [comment]
I must have some setting in my browser or something that is causing this then...

**Comment by lpalmes** [comment]
Did you manage to solve it @idkjs? It was working for me without an issue

**Comment by idkjs** [comment]
Not yet, brother. Was caught up in some reason stuff. I think I will download your repo and see how you did it. Let you know if I have some issues. Thank you very much for asking.  I just realized you are the same guy who was messing with relay bindings for reason on the discord channel. Do you mind sharing your bindings? It kinda kicking my ass.

**Comment by lpalmes** [comment]
Yes, sure, they are ugly as hell, let me tell you that. But i will upload at least a gist, maybe you could use them.

**Comment by idkjs** [comment]
Awesome, brother. If they work, that is enough for me. Can clean up after, contribute back if its any good! Very happy to hear that.

**Comment by lpalmes** [comment]
Here i have the bindings @idkjs,
https://gist.github.com/lpalmes/abe42b2cab2db9fa45575998588a35f3 , let me know if you have any questions

**Comment by idkjs** [comment]
you are the man. Im going to take a look it, probably tomorrow. keep you posted. Thank you, sir.

**Comment by idkjs** [comment]
Hey, brother. So question. You had to set your environment somewhere, right? Did you create a module for that?
